#ifndef DEFINITIONS_H
#define DEFINITIONS_H

typedef enum {
    // 00 binary
    TETRALATH_COLOR_NONE = 0,

    // 01 binary
    TETRALATH_COLOR_WHITE = 1,

    // 10 binary
    TETRALATH_COLOR_BLACK = 2
} TETRALATH_COLOR;

// 11 binary
#define TETRALATH_COLOR_MASK 3

static inline TETRALATH_COLOR flip_color(TETRALATH_COLOR color) {
    return (TETRALATH_COLOR)(color ^ TETRALATH_COLOR_MASK);
}

typedef enum {
    // 0000000000 binary
    TETRALATH_RESULT_ALPHA_MIN = 0,

    // 0000000001 binary
    TETRALATH_RESULT_LOSS = 1,

    // 0000111111 binary
    TETRALATH_RESULT_ABOUT_TO_LOSE = 63,

    // 0001000000 binary
    TETRALATH_RESULT_CLOSER_TO_LOSING = 64,

    // 011111111 binary
    TETRALATH_RESULT_NONE_MIN = 254,

    // 011111110 binary
    TETRALATH_RESULT_DRAW_MIN = 255,

    // 100000000 binary
    TETRALATH_RESULT_DRAW_MAX = 256,

    // 100000001 binary
    TETRALATH_RESULT_NONE_MAX = 257,

    // 110111111 binary
    TETRALATH_RESULT_CLOSER_TO_WINNING = 447,

    // 111000000 binary
    TETRALATH_RESULT_ABOUT_TO_WIN = 448,

    // 111111110 binary
    TETRALATH_RESULT_WIN = 510,

    // 111111111 binary
    TETRALATH_RESULT_BETA_MAX = 511
} TETRALATH_RESULT;

#define TETRALATH_RESULT_MASK 511

static inline TETRALATH_RESULT flip_result(TETRALATH_RESULT result) {
    return (TETRALATH_RESULT)(result ^ TETRALATH_RESULT_MASK);
}

typedef enum {
    TETRALATH_SEQUENCE_NONE = 0,
    TETRALATH_SEQUENCE_TRIPLET = 1,
    TETRALATH_SEQUENCE_QUADRUPLET = 2,
    TETRALATH_SEQUENCE_NEAR_TRIPLET_1 = 3,
    TETRALATH_SEQUENCE_NEAR_TRIPLET_2 = 4,
    TETRALATH_SEQUENCE_NEAR_QUADRUPLET_1 = 5,
    TETRALATH_SEQUENCE_NEAR_QUADRUPLET_2 = 6,
} TETRALATH_SEQUENCE;

typedef enum {
    TETRALATH_STATE_RUNNING = 0,
    TETRALATH_STATE_ENDING = 1,
    TETRALATH_STATE_QUITTING = 2
} TETRALATH_STATE;

typedef enum {
    TETRALATH_AI_MODE_NONE = 0,
    TETRALATH_AI_MODE_FRIENDLY = 1,
    TETRALATH_AI_MODE_RUTHLESS = 2
} TETRALATH_AI_MODE;

#define TETRALATH_BOARD_SIZE 61
#define TETRALATH_NUMBER_OF_COLORS 2
#define TETRALATH_POSITION_NONE (-1)
#define TETRALATH_DEFAULT_TIME_LIMIT_IN_SECONDS 5
#define TETRALATH_DEFAULT_NUMBER_OF_THREADS 2
#define TETRALATH_DEFAULT_MINIMAX_MAXIMUM_DEPTH 61
#define TETRALATH_SHOW_DEBUG_INFO 0

#endif
