#ifndef DEFINITIONS_H
#define DEFINITIONS_H

typedef enum {
    // Can represent an empty position.
    // 00 binary
    TETRALATH_COLOR_NONE = 0, //

    // Can represent a position occupied by a white piece.
    // 01 binary
    TETRALATH_COLOR_WHITE = 1,

    // Can represent a position occupied by a black piece.
    // 10 binary
    TETRALATH_COLOR_BLACK = 2,

    // Can represent a position outside the board.
    // 11 binary
    TETRALATH_COLOR_INVALID = 3,
} TETRALATH_COLOR;

#define TETRALATH_NUMBER_OF_COLORS 2
#define TETRALATH_FIRST_MOVE_COLOR TETRALATH_COLOR_WHITE

// Mask used with XOR to flip between colors.
// 11 binary
#define TETRALATH_COLOR_MASK 3

_Static_assert((((int)TETRALATH_COLOR_WHITE) ^ TETRALATH_COLOR_MASK) == ((int)TETRALATH_COLOR_BLACK), "TETRALATH_COLOR_WHITE must be flippable into TETRALATH_COLOR_BLACK");
_Static_assert((((int)TETRALATH_COLOR_BLACK) ^ TETRALATH_COLOR_MASK) == ((int)TETRALATH_COLOR_WHITE), "TETRALATH_COLOR_BLACK must be flippable into TETRALATH_COLOR_WHITE");

// Flips between white and black colors with a simple XOR operation, without the
// need for if/else conditionals.
static inline TETRALATH_COLOR flip_color(const TETRALATH_COLOR color) {
    return (TETRALATH_COLOR)(color ^ TETRALATH_COLOR_MASK);
}

typedef enum {
    /*
    Numbers less than 64 (TETRALATH_MINIMUM_RESULT_VALUE) are reserved to
    represent the next move in board states where the game is ongoing but the
    next move is known due to some kind of forced move/trap situation.
    */

    // 001000000 binary
    TETRALATH_RESULT_INFINITY_MIN = 64,

    // 001000001 binary
    TETRALATH_RESULT_LOSS = 65,
    TETRALATH_RESULT_LOSS_MIN = 65,

    // 010000001 binary
    TETRALATH_RESULT_LOSS_MAX = 129,

    // 010000010 binary
    TETRALATH_RESULT_ABOUT_TO_LOSE = 130,

    // 011111110 binary
    TETRALATH_RESULT_NONE_MIN = 254,

    // 011111111 binary
    TETRALATH_RESULT_DRAW_MIN = 255,

    // 100000000 binary
    TETRALATH_RESULT_DRAW = 256,
    TETRALATH_RESULT_DRAW_MAX = 256,

    // 100000001 binary
    TETRALATH_RESULT_NONE = 257,
    TETRALATH_RESULT_NONE_MAX = 257,

    // 101111101 binary
    TETRALATH_RESULT_ABOUT_TO_WIN = 381,

    // 101111110 binary
    TETRALATH_RESULT_WIN_MIN = 382,

    // 110111110 binary
    TETRALATH_RESULT_WIN = 446,
    TETRALATH_RESULT_WIN_MAX = 446,

    // 110111111 binary
    TETRALATH_RESULT_INFINITY_MAX = 447,
} TETRALATH_RESULT;

#define TETRALATH_MINIMUM_RESULT_VALUE TETRALATH_RESULT_INFINITY_MIN

typedef enum {
    TETRALATH_SEQUENCE_NONE = 0,
    TETRALATH_SEQUENCE_TRIPLET = 1,
    TETRALATH_SEQUENCE_QUADRUPLET = 2,
    TETRALATH_SEQUENCE_NEAR_TRIPLET_1 = 3,
    TETRALATH_SEQUENCE_NEAR_TRIPLET_2 = 4,
    TETRALATH_SEQUENCE_NEAR_TRIPLET_3 = 5,
    TETRALATH_SEQUENCE_NEAR_QUADRUPLET_1 = 6,
    TETRALATH_SEQUENCE_NEAR_QUADRUPLET_2 = 7,
} TETRALATH_SEQUENCE;

typedef enum {
    TETRALATH_STATE_NONE = 0,
    TETRALATH_STATE_RUNNING = 1,
    TETRALATH_STATE_ENDING = 2,
    TETRALATH_STATE_QUITTING = 3,
} TETRALATH_STATE;

typedef enum {
    TETRALATH_AI_MODE_NONE = 0,
    TETRALATH_AI_MODE_MERCIFUL = 1,
    TETRALATH_AI_MODE_RUTHLESS = 2,
} TETRALATH_AI_MODE;

typedef enum {
    TETRALATH_AI_STRATEGY_NONE = 0,
    TETRALATH_AI_STRATEGY_OFFENSIVE = 1,
    TETRALATH_AI_STRATEGY_DEFENSIVE = 2,
} TETRALATH_AI_STRATEGY;

#define TETRALATH_CPU_CACHE_LINE_BYTES 64

#define TETRALATH_ALLOCATED_BOARD_LENGTH 64

#define TETRALATH_ALLOCATED_BOARD_BYTES (TETRALATH_ALLOCATED_BOARD_LENGTH * sizeof(TETRALATH_COLOR))
_Static_assert((TETRALATH_ALLOCATED_BOARD_BYTES % TETRALATH_CPU_CACHE_LINE_BYTES) == 0, "TETRALATH_ALLOCATED_BOARD_BYTES must be a multiple of TETRALATH_CPU_CACHE_LINE_BYTES");

#define TETRALATH_BOARD_SIZE 61
#define TETRALATH_POSITION_NONE (-1)
#define TETRALATH_DEFAULT_TIME_LIMIT_IN_SECONDS 5
#define TETRALATH_DEFAULT_MINIMAX_MINIMUM_DEPTH 1
#define TETRALATH_DEFAULT_MINIMAX_MAXIMUM_DEPTH 61
#define TETRALATH_IGNORE_PARTIALLY_COMPLETED_SEARCHES 0
#define TETRALATH_SHOW_DEBUG_INFO 0

#endif
